# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=my_root_password
      - MARIADB_USER=my_user
      - MARIADB_PASSWORD=my_password
      - MARIADB_DATABASE=my_database
    ports:
      - '3306:3306'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'

  moodle:
    image: 'bitnami/moodle:latest'
    environment:
      - MOODLE_DATABASE_TYPE=mariadb
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=my_database
      - MOODLE_DATABASE_USER=my_user
      - MOODLE_DATABASE_PASSWORD=my_password
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'moodle_data:/bitnami/moodle'

volumes:
  mariadb_data:
    driver: local
  moodle_data:
    driver: local